// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ozdilek.PM.UserDirectoryService.Infrastructure.Persistence;

#nullable disable

namespace Ozdilek.PM.UserDirectoryService.Infrastructure.Migrations
{
    [DbContext(typeof(UserDirectoryDbContext))]
    [Migration("20260727080907_AddAuthentication")]
    partial class AddAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HeadEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Name = "Arge Proje Müdürlüğü"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Name = "Proje Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Name = "BT Müdürlüğü"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Name = "Teknik Müdürlük"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "BT Departmanı"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "E Ticaret Departmanı"
                        });
                });

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RolesCsv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("roles_csv");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            DisplayName = "Ahmet Görür",
                            Email = "ahmet.gorur@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Admin,ProjectManager,Approver",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            DisplayName = "Selin Güler",
                            Email = "selin.guler@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "ProjectManager,Approver",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            DisplayName = "Selim Akar",
                            Email = "selim.akar@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "ProjectManager",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            DisplayName = "Gamze Demir",
                            Email = "gamze.demir@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member,Approver",
                            Title = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222205"),
                            DisplayName = "Ahmet Gür",
                            Email = "ahmet.gur@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222206"),
                            DisplayName = "Merve Tezciler",
                            Email = "merve.tezciler@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Birim Sorumlusu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
