// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ozdilek.PM.UserDirectoryService.Infrastructure.Persistence;

#nullable disable

namespace Ozdilek.PM.UserDirectoryService.Infrastructure.Migrations
{
    [DbContext(typeof(UserDirectoryDbContext))]
    [Migration("20260727063016_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RolesCsv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("roles_csv");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Arge Proje Müdürlüğü",
                            DisplayName = "Ahmet Görür",
                            Email = "ahmet.gorur@example.com",
                            IsActive = true,
                            RolesCsv = "Admin,ProjectManager,Approver",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Proje Yönetimi",
                            DisplayName = "Selin Güler",
                            Email = "selin.guler@example.com",
                            IsActive = true,
                            RolesCsv = "ProjectManager,Approver",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "BT Müdürlüğü",
                            DisplayName = "Selim Akar",
                            Email = "selim.akar@example.com",
                            IsActive = true,
                            RolesCsv = "ProjectManager",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Teknik Müdürlük",
                            DisplayName = "Gamze Demir",
                            Email = "gamze.demir@example.com",
                            IsActive = true,
                            RolesCsv = "Member,Approver",
                            Title = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "BT Departmanı",
                            DisplayName = "Ahmet Gür",
                            Email = "ahmet.gur@example.com",
                            IsActive = true,
                            RolesCsv = "Member",
                            Title = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "E Ticaret Departmanı",
                            DisplayName = "Merve Tezciler",
                            Email = "merve.tezciler@example.com",
                            IsActive = true,
                            RolesCsv = "Member",
                            Title = "Birim Sorumlusu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
