// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ozdilek.PM.UserDirectoryService.Infrastructure.Persistence;

#nullable disable

namespace Ozdilek.PM.UserDirectoryService.Infrastructure.Migrations
{
    [DbContext(typeof(UserDirectoryDbContext))]
    [Migration("20260729220622_ExpandDepartmentEmployeeDirectory")]
    partial class ExpandDepartmentEmployeeDirectory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HeadEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeadEmployeeId")
                        .IsUnique()
                        .HasFilter("\"HeadEmployeeId\" IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111101"),
                            IsActive = true,
                            Name = "Arge Proje Müdürlüğü"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111102"),
                            IsActive = true,
                            Name = "Proje Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111103"),
                            IsActive = true,
                            Name = "BT Müdürlüğü"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111104"),
                            IsActive = true,
                            Name = "Teknik Müdürlük"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = false,
                            Name = "BT Departmanı"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadEmployeeId = new Guid("11111111-1111-1111-1111-111111111106"),
                            IsActive = true,
                            Name = "E Ticaret Departmanı"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Hukuk Departmanı"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Muhasebe Departmanı"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Pazarlama Departmanı"
                        });
                });

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RolesCsv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("roles_csv");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            DisplayName = "Ahmet Görür",
                            Email = "ahmet.gorur@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            DisplayName = "Selin Güler",
                            Email = "selin.guler@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            DisplayName = "Selim Akar",
                            Email = "selim.akar@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            DisplayName = "Gamze Demir",
                            Email = "gamze.demir@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            DisplayName = "Ahmet Gür",
                            Email = "ahmet.gur@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "BT Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222206"),
                            DisplayName = "Merve Tezciler",
                            Email = "merve.tezciler@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Admin",
                            Email = "admin",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEJwWJoSAdPaJR1mIqlm7+oh0ZK5GfExiWZ6dpEBvWRw/RAcw8mO2VHEEkcDjgm+YMg==",
                            RolesCsv = "Admin",
                            Title = "Sistem Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            DisplayName = "Mustafa Altekin",
                            Email = "mustafa.altekin@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "ProjectManager",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222207"),
                            DisplayName = "Zeynep Mutlu",
                            Email = "zeynep.mutlu@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Hukuk Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222208"),
                            DisplayName = "Elif Edem",
                            Email = "elif.edem@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Muhasebe Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222209"),
                            DisplayName = "Ece Erenli",
                            Email = "ece.erenli@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Pazarlama Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            DisplayName = "Onur Yalçın",
                            Email = "onur.yalcin@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Proje Planlama Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            DisplayName = "Derya Satı",
                            Email = "derya.sati@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Maliyet Analisti"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            DisplayName = "Yasin Ters",
                            Email = "yasin.ters@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Kıdemli Proje Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            DisplayName = "Zeynel Mutlu",
                            Email = "zeynel.mutlu@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Proje Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            DisplayName = "Osman Fır",
                            Email = "osman.fir@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            DisplayName = "Ali Eker",
                            Email = "ali.eker@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Sistem Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            DisplayName = "Defne Satlı",
                            Email = "defne.satli@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Teknik Satın Alma Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            DisplayName = "Erkan Akacı",
                            Email = "erkan.akaci@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Teknik Uzman"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222206"),
                            DisplayName = "Deniz Korkmaz",
                            Email = "deniz.korkmaz@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "E-Ticaret Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222206"),
                            DisplayName = "Burcu Aydın",
                            Email = "burcu.aydin@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Dijital Operasyon Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222207"),
                            DisplayName = "Selin Akar",
                            Email = "selin.akar@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Hukuk Müşaviri"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222207"),
                            DisplayName = "Ceren Kaya",
                            Email = "ceren.kaya@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Sözleşme Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222208"),
                            DisplayName = "Gizem Topcu",
                            Email = "gizem.topcu@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Muhasebe Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222208"),
                            DisplayName = "Eylül Arslan",
                            Email = "eylul.arslan@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Bütçe ve Raporlama Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222209"),
                            DisplayName = "Zeynep Paslı",
                            Email = "zeynep.pasli@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Marka Uzmanı"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222209"),
                            DisplayName = "Elif Ekinci",
                            Email = "elif.ekinci@example.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAx2a0oaK6EvoWj2gBFdMPlHt99WzVLyJyMZqkukRL5JS37Z7R2HEfVwgALpYIr5nQ==",
                            RolesCsv = "Member",
                            Title = "Pazarlama Uzmanı"
                        });
                });

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Department", b =>
                {
                    b.HasOne("Ozdilek.PM.UserDirectoryService.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("HeadEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Ozdilek.PM.UserDirectoryService.Domain.Employee", b =>
                {
                    b.HasOne("Ozdilek.PM.UserDirectoryService.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
